#!/bin/bash

# $1 -- command $2 -- container name

wrong_usage() {
  echo "Wrong usage! Available commands:"
  echo "start    | st   -- start server"
  echo "stop     | sp   -- stop server"
  echo "restart  | r    -- restart server"
}

if [[ $# -ne 1 ]]; then
  wrong_usage
  exit
fi

case $1 in
start | st)
  docker start $2
  ;;

stop | sp)
  docker stop $2
  ;;

restart | r)
  docker restart $2
  ;;
*)
  wrong_usage

  ;;
esac
